#!/usr/bin/env bash

USAGE="$0 light|dark|solarized-light|solarized-dark|harmonic-light|harmonic-dark"

TERMITE_CONF_FOLDER=~/.config/termite
THEME=$1

change_theme() {
    echo "# THIS FILE HAS BEEN AUTOGENERATED. DO NOT CHANGE MANUALLY!" | \
        cat - /tmp/termite-switch-theme.hint $TERMITE_CONF_FOLDER/config.base $TERMITE_CONF_FOLDER/themes/$1 > $TERMITE_CONF_FOLDER/config
    killall -USR1 termite || true
}

case $THEME in
    solarized-light) change_theme solarized-light ;;
    solarized-dark) change_theme solarized-dark ;;
    light|harmonic-light) change_theme base16-harmonic-light ;;
    dark|harmonic-dark) change_theme base16-harmonic-dark ;;
    *) echo $USAGE ;;
esac

